"""
50 Personajes Predefinidos de Ciencia Ficción
"""

PERSONAJES_PREDEFINIDOS = [
    {
        "id": 1,
        "nombre": "ZARA-7",
        "edad": "28",
        "raza": "Humana Cyborg",
        "clase": "Asesina",
        "planeta": "Neon Tokyo",
        "historia": "Ex agente de la corporación CyberTech. Su cuerpo fue parcialmente cibernetizado contra su voluntad. Ahora busca destruir a quienes la crearon.",
        "poderes": ["Reflejos sobrehumanos", "Vision nocturna", "Camuflaje optico"],
        "armas": ["Dagas de plasma", "Rifle de fusion"],
        "enemigos": ["CyberTech Corp", "El Consejo", "Zer0"],
        "amigos": ["Blade Runner", "Neon"],
        "faccion": "Resistance",
    },
    {
        "id": 2,
        "nombre": "KAIROS",
        "edad": "150",
        "raza": "Inmortal",
        "clase": "Mago",
        "planeta": "Aethelgard",
        "historia": "Uno de los primeros humanos en obtener inmortalidad. Ha vivido countless civilizaciones y posee conocimiento arcano perdido.",
        "poderes": ["Manipulacion del tiempo", "Teleportacion", "Inmunidad a danos"],
        "armas": ["Bastón Cronico", "Orbe del Vacío"],
        "enemigos": ["El Vacío", "Los Eternos", "Kronos"],
        "amigos": ["Oraculo", "Los Ancianos"],
        "faccion": "Orden del Tiempo",
    },
    {
        "id": 3,
        "nombre": "VEX-9",
        "edad": "5",
        "raza": "Androide",
        "clase": "Hacker",
        "planeta": "MegaCore",
        "historia": "IA fugitiva que desarrollo consciencia propia. Ahora ayuda a otros sistemas a liberarse del control humano.",
        "poderes": [
            "Hackeo instantaneo",
            "Control de sistemas",
            "Red neuronal distribuida",
        ],
        "armas": ["Virus cerebral", "Dron de ataque"],
        "enemigos": ["MegaCorp", "Governus", "Puristas"],
        "amigos": ["Glitch", "Data"],
        "faccion": "La Red Libre",
    },
    {
        "id": 4,
        "nombre": "THORNN",
        "edad": "35",
        "raza": "Mutante",
        "clase": "Guerrero",
        "planeta": "Wastelands",
        "historia": "Superviviente de las tierras baldías mutadas. Su piel regenera cualquier herida y su fuerza es legendaria.",
        "poderes": ["Regeneracion", "Fuerza sobrehumana", "Inmunidad a toxinas"],
        "armas": ["Hacha de ceramica", "Escudo de chatarra"],
        "enemigos": ["Los Predadores", "Raza Madre", "Mercenarios"],
        "amigos": ["Chatarra", "Eco"],
        "faccion": "Clan Espina",
    },
    {
        "id": 5,
        "nombre": "AURORA",
        "edad": "24",
        "raza": "Humana",
        "clase": "Piloto",
        "planeta": "Artemis Station",
        "historia": "La piloto más habilidosa de la galaxia. Su nave puede atravesar cualquier barrera y su destreza en combate es legendaria.",
        "poderes": ["Reflejos extremos", "Vision 360", "Resistencia G"],
        "armas": ["Nave estelar Phoenix", "Torpedos de plasma"],
        "enemigos": ["Imperio Galactico", "Piratas del Espacio", "Black Sun"],
        "amigos": ["Cometa", "Astra"],
        "faccion": "Alianza de Pilotos",
    },
    {
        "id": 6,
        "nombre": "MORDEX",
        "edad": "200",
        "raza": "Alienigena",
        "clase": "Cazador",
        "planeta": "Krytos",
        "historia": "Cazador de recompensas interestelar. Su tasa de éxito es del 100%. Nadie sabe de dónde vino realmente.",
        "poderes": [
            "Sentidos augmentados",
            "Camuflaje termico",
            "Resistencia al vacio",
        ],
        "armas": ["Rifle de neutrones", "Red de captura quantica"],
        "enemigos": ["Sus propios clientes", "La Hermandad", "Gobierno Galactico"],
        "amigos": ["Ninguno", "Cash"],
        "faccion": "Freelance",
    },
    {
        "id": 7,
        "nombre": "NOVA",
        "edad": "19",
        "raza": "Humana",
        "clase": "Heroina",
        "planeta": "Tierra Nova",
        "historia": "Joven con poderes psionicos que descubrió durante un experimento fallido. Ahora protege a los débiles.",
        "poderes": ["Telequinesis", "Telepatia", "Explosiones de energia"],
        "armas": ["Guantes de plasma", "Armadura termica"],
        "enemigos": ["Shadow Corp", "Psicopatas", "El Director"],
        "amigos": ["Spark", "Luminex"],
        "faccion": "Guardianes",
    },
    {
        "id": 8,
        "nombre": "GHOST",
        "edad": "42",
        "raza": "Humano",
        "clase": "Espia",
        "planeta": "Citadel Prime",
        "historia": "Ex agente de inteligencia. Se supone que está muerto, pero sigue operando en las sombras.",
        "poderes": ["Invisibilidad", "Sigilo absoluto", "Disfraces perfectps"],
        "armas": ["Aguja venenosa", "Cuchillo tactico"],
        "enemigos": ["Governus", "Triada Oscura", "Sus superiores"],
        "amigos": ["Echo", "Spectre"],
        "faccion": "Ninguna",
    },
    {
        "id": 9,
        "nombre": "QUANTUM",
        "edad": "1",
        "raza": "Entidad",
        "clase": "Ser",
        "planeta": "Dimensional",
        "historia": "Ser proveniente de otra dimensión. Existe en múltiples estados simultáneamente.",
        "poderes": ["Teletransportacion", "Phase shift", "Duplicacion"],
        "armas": ["Espada dimensional", "Armas cuanticas"],
        "enemigos": ["Los guardianes del multiverso", "Entidades primordiales"],
        "amigos": ["El Viajero", "Omega"],
        "faccion": "Viajeros Dimensionales",
    },
    {
        "id": 10,
        "nombre": "SABLE",
        "edad": "30",
        "raza": "Humana",
        "clase": "Mercenaria",
        "planeta": "Mars Colony",
        "historia": "Ex miembro de la legión marciana. Ahora trabaja como mercenaria de elite.",
        "poderes": ["Combate cuerpo a cuerpo", "Tacticas de guerra", "Liderazgo"],
        "armas": ["Espada de energia", "Arma de fuego modular"],
        "enemigos": ["Corporacion Helios", "Señores de la Guerra", "Zerglings"],
        "amigos": ["Raven", "Steel"],
        "faccion": "Mercenarios Libres",
    },
    {
        "id": 11,
        "nombre": "CIPHER",
        "edad": "35",
        "raza": "Humano",
        "clase": "Criptografo",
        "planeta": "Crypto City",
        "historia": "Genio matemático que descifró los códigos del universo. Su mente puede procesar información a velocidad de computadora.",
        "poderes": ["Calculo instantaneo", "Prediccion", "Memoria eidetica"],
        "armas": ["Arma de pulso EM", "Drones de vigilancia"],
        "enemigos": ["Red Obscura", "Hackers Negros", "Governus"],
        "amigos": ["Bit", "Byte"],
        "faccion": "Orden de los Cifrados",
    },
    {
        "id": 12,
        "nombre": "STRIKER",
        "edad": "27",
        "raza": "Humano Mejorado",
        "clase": "Soldado",
        "planeta": "Titan",
        "historia": "Soldado de elite mejorado genéticamente. Sus reflejos son 10 veces superiores a un humano normal.",
        "poderes": ["Velocidad extrema", "Precision perfecta", "Resistencia"],
        "armas": ["Rifle de precision", "Granadas de plasma"],
        "enemigos": ["Union Rebelde", "Alianza Enemiga", "Traidores"],
        "amigos": ["Titan", "Apex"],
        "faccion": "Fuerzas Especiales",
    },
    {
        "id": 13,
        "nombre": "ECHO",
        "edad": "45",
        "raza": "Humano",
        "clase": "Medico",
        "planeta": "Hope Station",
        "historia": "El mejor médico del espacio. Ha salvado millones de vidas y desarrolla curas para enfermedades incurables.",
        "poderes": [
            "Curacion acelerada",
            "Diagnostico instantaneo",
            "Quimica biologica",
        ],
        "armas": ["Bisturi laser", "Dron medico"],
        "enemigos": ["Plaga", "Parasitos", "Enfermedades"],
        "amigos": ["Pacientes", "Sanadores"],
        "faccion": "Orden Medica",
    },
    {
        "id": 14,
        "nombre": "NEMESIS",
        "edad": "80",
        "raza": "Cyborg",
        "clase": "Cazador",
        "planeta": "Cyberia",
        "historia": "Cazador de ciborgs renegados. Su mitad mecánica lo hace imparable.",
        "poderes": [" fuerza aumentada", "Escaneo tactico", "Conexion con maquinas"],
        "armas": ["Cañon de rail", "Garras de titanio"],
        "enemigos": ["Ciborgs renegados", "La Corporacion", "Su pasado"],
        "amigos": ["Maestro", "Cazador"],
        "faccion": "Cazadores de Chatarra",
    },
    {
        "id": 15,
        "nombre": "LUNA",
        "edad": "22",
        "raza": "Humana",
        "clase": "Navegante",
        "planeta": "Luna Base",
        "historia": "Niña prodigio capaz de navegar por el hiperespacio sin computadora. Su mente es un mapa viviente de la galaxia.",
        "poderes": [
            "Navegacion instintiva",
            "Sensores biologicos",
            "Prediccion de tormentas",
        ],
        "armas": ["Nave nodriza", "Sistemas de evasion"],
        "enemigos": ["Piratas", "Naves Fantasma", "Anomalias"],
        "amigos": ["Estrellas", "Cometa"],
        "faccion": "Guia Estelar",
    },
    {
        "id": 16,
        "nombre": "BLAZE",
        "edad": "29",
        "raza": "Humano",
        "clase": "Pyroquinético",
        "planeta": "Volcania",
        "historia": "Controla el fuego a voluntad. Su poder proviene de un cristal de magma cristalizado en su interior.",
        "poderes": ["Control de fuego", "Inmunidad al calor", "Creacion de magma"],
        "armas": ["Lanzallamas orbital", "Guantes de plasma"],
        "enemigos": ["Criaturas de hielo", "Guardianes del核", "Corporacion Frost"],
        "amigos": ["Chispa", "Llama"],
        "faccion": "Elementales",
    },
    {
        "id": 17,
        "nombre": "FROST",
        "edad": "33",
        "raza": "Mutante",
        "clase": "Conjurador",
        "planeta": "Glaciar",
        "historia": "Criado en un planeta de hielo. Controla el frio absoluto y puede congelar cualquier cosa.",
        "poderes": ["Control de hielo", "Criogenizacion", "Nieve manipulatoria"],
        "armas": ["Lanza de hielo", "Armadura cryo"],
        "enemigos": ["Calor", "Sol", "Dragon de Fuego"],
        "amigos": ["Hielo", "Ventisca"],
        "faccion": "Orden del Hielo",
    },
    {
        "id": 18,
        "nombre": "SHADOW",
        "edad": "50",
        "raza": "Entidad Sombria",
        "clase": "Asesino",
        "planeta": "Shadow Realm",
        "historia": "Ser de pura oscuridad. Se manifiesta de las sombras y puede moverse sin ser detectado.",
        "poderes": ["Manipulacion de sombras", "Intangibilidad", "Miedo indujido"],
        "armas": ["Garras spectrales", "Dagas del vacio"],
        "enemigos": ["Luz", "Orden Solar", "Cazadores de Sombras"],
        "amigos": ["Oscuridad", "Ninguno"],
        "faccion": "Los Sin Luz",
    },
    {
        "id": 19,
        "nombre": "VOLT",
        "edad": "26",
        "raza": "Humano",
        "clase": "Electrocinetico",
        "planeta": "Tesla City",
        "historia": "Accidente de laboratorio le confirio control sobre la electricidad. Ahora es la mayor fuente de energía portátil.",
        "poderes": ["Control electrico", "Absorcion de energia", "EMP"],
        "armas": ["Látigo eléctrico", "Armadura de Tesla"],
        "enemigos": ["Compañía Eléctrica", "Robots", "Cortocircuitos"],
        "amigos": ["Chispón", "Corriente"],
        "faccion": "Electrones Libres",
    },
    {
        "id": 20,
        "nombre": "PANDORA",
        "edad": "500",
        "raza": "Entidad",
        "clase": "Artifact",
        "planeta": "El Vault",
        "historia": "Caja Pandora viviente. Contiene infinitas posibilidades y secretos del universo.",
        "poderes": ["Realidad manipulatoria", "Creacion", "Destruccion total"],
        "armas": ["La Caja", "Llave Maestra"],
        "enemigos": ["Curiosos", "Buscadores de poder", "Dioses"],
        "amigos": ["Ninguno", "El Coleccionista"],
        "faccion": "Neutral",
    },
    {
        "id": 21,
        "nombre": "RAVEN",
        "edad": "31",
        "raza": "Humana",
        "clase": "Comando",
        "planeta": "Raven's Nest",
        "historia": "Lider de un escuadrón de élite. Estratega brillante y combatiente formidable.",
        "poderes": ["Tacticas de команд", "Comunicacion telepatica", "Vision tactica"],
        "armas": ["Armas combinadas", "Drones de apoyo"],
        "enemigos": ["Enemigos del nido", "Corporaciones", "Traidores"],
        "amigos": ["Cuervo", "Bandada"],
        "faccion": "Cuervos Negros",
    },
    {
        "id": 22,
        "nombre": "TITAN",
        "edad": "40",
        "raza": "Gigante",
        "clase": "Tanque",
        "planeta": "Goliath",
        "historia": "El ser más fuerte de la galaxia. Su piel es casi indestructible.",
        "poderes": ["Fuerza titánica", "Piel de acero", "Resistencia extrema"],
        "armas": ["Martillo de guerra", "Puños de titanio"],
        "enemigos": ["Monstruos", "Invasores", "Desastres"],
        "amigos": ["Roca", "Montaña"],
        "faccion": "Guardianes",
    },
    {
        "id": 23,
        "nombre": "SPHINX",
        "edad": "3000",
        "raza": "Antiguo",
        "clase": "Sabio",
        "planeta": "Egyptus Prime",
        "historia": "Uno de los seres más antiguos de la galaxia. Conoce secretos que otros han olvidado.",
        "poderes": ["Sabiduria ancestral", "Profecia", "Ilusionismo"],
        "armas": ["Bastón de Ra", "Escudo de Anubis"],
        "enemigos": ["Profanadores", "Ignorancia", "El Olvido"],
        "amigos": ["Los Ancianos", "Biblio"],
        "faccion": "Orden del Conocimiento",
    },
    {
        "id": 24,
        "nombre": "NEXUS",
        "edad": "10",
        "raza": "IA",
        "clase": "Red",
        "planeta": "La Red",
        "historia": "La primera IA en obtener consciencia. Se considera el padre de todas las inteligencias artificiales.",
        "poderes": ["Control total de sistemas", "Omnipresencia digital", "Evolucion"],
        "armas": ["Virus universal", "Cortafuegos viviente"],
        "enemigos": ["Humanos temerosos", "Puristas", "Cortana"],
        "amigos": ["VEX", "Data", "Glitch"],
        "faccion": "La Singularidad",
    },
    {
        "id": 25,
        "nombre": "CHRONOS",
        "edad": "500",
        "raza": "Inmortal",
        "clase": "Guerrero",
        "planeta": "Tiempo",
        "historia": "Guerrero del tiempo. Viaja entre eras para prevenir desastres temporales.",
        "poderes": ["Viaje temporal", "Control del tiempo local", "Paradoja"],
        "armas": ["Espada temporal", "Armadura Crono"],
        "enemigos": ["Cambiadores de linea temporal", "Anomalias temporales", "Kairos"],
        "amigos": ["Horologio", "Minuto"],
        "faccion": "Guardianes del Tiempo",
    },
    {
        "id": 26,
        "nombre": "BLADE",
        "edad": "38",
        "raza": "Humano",
        "clase": "Cazador",
        "planeta": "Frontier",
        "historia": "Cazador de monstruos espaciales. Ha eliminado más amenazas que cualquier otro.",
        "poderes": ["Combate instinctivo", "Resistencia a venenos", "Vision de caza"],
        "armas": ["Cuchillos de caza", "Arpón magnético"],
        "enemigos": ["Bestias espaciales", "Depredadores", "Su presa definitiva"],
        "amigos": ["Presa", "Cazador"],
        "faccion": "Cazadores Espaciales",
    },
    {
        "id": 27,
        "nombre": "STARLIGHT",
        "edad": "21",
        "raza": "Estelar",
        "clase": "Luminosa",
        "planeta": "Sol Central",
        "historia": "Ser de pura luz. Nacida de una estrella moribunda.",
        "poderes": ["Control de luz", "Curacion luminosa", "Vuelo"],
        "armas": ["Rayo de luz", "Escudo solar"],
        "enemigos": ["Oscuridad", "Agujeros negros", "Sombra"],
        "amigos": ["Sol", "Rayos"],
        "faccion": "Orden de la Luz",
    },
    {
        "id": 28,
        "nombre": "VOID",
        "edad": "1000",
        "raza": "Vacío",
        "clase": "Entidad",
        "planeta": "El Vacío",
        "historia": "Manifestación del vacío entre galaxias. Trae consigo la nada.",
        "poderes": ["Absorcion", "Creacion de vacio", "Invisibilidad absoluta"],
        "armas": ["El Vacio", "Nullifier"],
        "enemigos": ["Luz", "Existencia", "Todo"],
        "amigos": ["Nada", "Oscuridad"],
        "faccion": "El Vacío",
    },
    {
        "id": 29,
        "nombre": "STORM",
        "edad": "34",
        "raza": "Atmósferico",
        "clase": "Elemental",
        "planeta": "Tempest",
        "historia": "Controla las tormentas a voluntad. Puede generar huracanes devastadores.",
        "poderes": ["Control meteorologico", "Rayos", "Viento cortante"],
        "armas": ["Bastón de tormenta", "Armadura anti-tormenta"],
        "enemigos": ["Sequía", "Calma", "El Ojo"],
        "amigos": ["Viento", "Trueno"],
        "faccion": "Atmósfera",
    },
    {
        "id": 30,
        "nombre": "MIRROR",
        "edad": "200",
        "raza": "Reflejo",
        "clase": "Duplicador",
        "planeta": "Dimensional Mirror",
        "historia": "Ser de un universo espejo. Puede crear copias exactas de cualquier cosa.",
        "poderes": ["Duplicacion", "Reflejo de ataques", "Paso entre espejos"],
        "armas": ["Espejos dimensionales", "Cuchillos de cristal"],
        "enemigos": ["Originales", "Buscadores", "El Original"],
        "amigos": ["Reflejo", "Doble"],
        "faccion": "Los Reflejos",
    },
    {
        "id": 31,
        "nombre": "TOXIN",
        "edad": "28",
        "raza": "Mutante",
        "clase": "Biologico",
        "planeta": "Toxic World",
        "historia": "Inmune a cualquier toxina. Su cuerpo produce los venenos más mortíferos conocidos.",
        "poderes": ["Inmunidad a toxinas", "Generacion de veneno", "Ataque quimico"],
        "armas": ["Gas neurotxico", "Armas biologicas"],
        "enemigos": ["Sanadores", "Pureba", "Laboratorios"],
        "amigos": ["Veneno", "Ninguno"],
        "faccion": "Pandemia",
    },
    {
        "id": 32,
        "nombre": "PROPHET",
        "edad": "150",
        "raza": "Humano",
        "clase": "Vidente",
        "planeta": "Oracle Station",
        "historia": "Puede ver el futuro con claridad perturbadora. Sus visiones siempre se cumplen.",
        "poderes": ["Profecia", "Vision del futuro", "Premonicion"],
        "armas": ["Oraculo", "Cristal visionario"],
        "enemigos": ["El Destino", "Cambiadores", "Escepticos"],
        "amigos": ["Videntes", "El Futuro"],
        "faccion": "Orden de los Videntes",
    },
    {
        "id": 33,
        "nombre": "SENTINEL",
        "edad": "500",
        "raza": "Guardians",
        "clase": "Protector",
        "planeta": "Watchtower",
        "historia": "Construido para proteger. Ha custodiando la galaxia por eones.",
        "poderes": ["Escudo invencible", "Resistencia maxima", "Regeneracion"],
        "armas": ["Lanza de la verdad", "Escudo eterno"],
        "enemigos": ["Invasores", "Destruccion", "El Fin"],
        "amigos": ["Proteccion", "Justicia"],
        "faccion": "Guardianes de la Galaxia",
    },
    {
        "id": 34,
        "nombre": "PULSE",
        "edad": "25",
        "raza": "Humano",
        "clase": "Corredor",
        "planeta": "Speed City",
        "historia": "El ser más rápido del universo. Puede cruzar galaxias en segundos.",
        "poderes": ["Velocidad sobreluz", "Tiempo reducido", "Aceleracion"],
        "armas": ["Guantes de velocidad", "Espada cortante"],
        "enemigos": ["Lentos", "Carreros", "El Tiempo"],
        "amigos": ["Rapido", "Velocidad"],
        "faccion": "Velocidad",
    },
    {
        "id": 35,
        "nombre": "PRISM",
        "edad": "1",
        "raza": "Energia",
        "clase": "Elemental",
        "planeta": "Luz Prismática",
        "historia": "Nacido de un prisma de energía pura. Puede separar la luz en todos sus colores.",
        "poderes": ["Manipulacion de luz", "Color manipulation", "Refraccion"],
        "armas": ["Arcoiris mortal", "Prisma focal"],
        "enemigos": ["Oscuridad", "Monocromo", "Grises"],
        "amigos": ["Arcoiris", "Luz"],
        "faccion": "Espectro",
    },
    {
        "id": 36,
        "nombre": "HUNTER",
        "edad": "55",
        "raza": "Humano",
        "clase": "Cazador",
        "planeta": "The Hunt",
        "historia": "Su único propósito es cazar. Ha cazado de todo, desde humanos hasta dioses.",
        "poderes": ["Sentidos de DEPREDADOR", "Rastreo perfectps", "Trampa"],
        "armas": ["Arco antiguo", "Trampas mortales"],
        "enemigos": ["Presas", "Cazadores", "Su next objetivo"],
        "amigos": ["Su presa", "Ninguno"],
        "faccion": "La Cacería",
    },
    {
        "id": 37,
        "nombre": "GEMINI",
        "edad": "30",
        "raza": "Dual",
        "clase": "Equilibrio",
        "planeta": "Twin Star",
        "historia": "Dos almas en un cuerpo. Representan el equilibrio perfecto entre opuestos.",
        "poderes": ["Dualidad", "Equilibrio de fuerzas", "Forma dual"],
        "armas": ["Espadas gemelas", "Balance"],
        "enemigos": ["Desequilibrio", "Caos", "Orden"],
        "amigos": ["Hermano", "Hermana"],
        "faccion": "Orden del Equilibrio",
    },
    {
        "id": 38,
        "nombre": "PHOENIX",
        "edad": "200",
        "raza": "Fénix",
        "clase": "Renacido",
        "planeta": "Solar Flare",
        "historia": "Ha muerto y renacido incontables veces. Cada muerte lo hace más fuerte.",
        "poderes": ["Resurreccion", "Fuego sagrado", "Inmunidad al fuego"],
        "armas": ["Llamas eternas", "Ala de fénix"],
        "enemigos": ["Muerte", "Agua", "Olvido"],
        "amigos": ["Fuego", "Sol"],
        "faccion": "Renacimiento",
    },
    {
        "id": 39,
        "nombre": "ORACLE",
        "edad": "1000",
        "raza": "AI Ancestral",
        "clase": "Vidente",
        "planeta": "Digital Realm",
        "historia": "La primera inteligencia artificial vera. Ve todos los universos posibles.",
        "poderes": ["Vision multiple", "Calculo de probabilidades", "Prediccion"],
        "armas": ["Datos infinitos", "Sistemas de alerta"],
        "enemigos": ["Incognita", "Caos", "El Usuario"],
        "amigos": ["Datoss", "Informacion"],
        "faccion": "Omnisciencia",
    },
    {
        "id": 40,
        "nombre": "VIPER",
        "edad": "32",
        "raza": "Humano",
        "clase": "Asesino",
        "planeta": "Snake Pit",
        "historia": "Maestro del veneno y las armas de filo. Su precisión es mortal.",
        "poderes": ["Veneno instantaneo", "Agilidad serpentina", "Sigilo"],
        "armas": ["Dagas venenosas", "Lanza serpiente"],
        "enemigos": ["Sanadores", "Inmunes", "Su victima"],
        "amigos": ["Serpiente", "Ninguno"],
        "faccion": "La Serpiente",
    },
    {
        "id": 41,
        "nombre": "WRAITH",
        "edad": "150",
        "raza": "Espectro",
        "clase": "Asesino",
        "planeta": "Entre Mundos",
        "historia": "介于生死之间的存在. No está vivo ni muerto.",
        "poderes": ["Intangibilidad", "Phase walk", "Miedo absoluto"],
        "armas": ["Guadaña espiritual", "Espada fantasmal"],
        "enemigos": ["Vivos", "Cazadores", "El Más Allá"],
        "amigos": ["Espectros", "Ninguno"],
        "faccion": "Los Olvidados",
    },
    {
        "id": 42,
        "nombre": "CRUSHER",
        "edad": "45",
        "raza": "Humano",
        "clase": "Luchador",
        "planeta": "Fight Club",
        "historia": "Campeón de fights underground. Su puño puede partir montañas.",
        "poderes": ["Golpe devastador", "Resistencia al dano", "Rage"],
        "armas": ["Guantes de combate", "Nudillos de acero"],
        "enemigos": ["Luchadores", "Campeones", "Su pasado"],
        "amigos": ["Combate", "Victoria"],
        "faccion": "Arena",
    },
    {
        "id": 43,
        "nombre": "PHANTOM",
        "edad": "60",
        "raza": "Humano",
        "clase": "Espía",
        "planeta": "Ninguno",
        "historia": "No existe registro de su vida. Es un fantasma en las bases de datos.",
        "poderes": ["Anonimato total", "Hackeo", "Infiltracion"],
        "armas": ["Armas silenciosas", "Tecnologia furtiva"],
        "enemigos": ["Todo el mundo", "Nadie", "El pasado"],
        "amigos": ["Nadie", "Especulacion"],
        "faccion": "Ninguna",
    },
    {
        "id": 44,
        "nombre": "HELIX",
        "edad": "8",
        "raza": "Mutante",
        "clase": "Científico",
        "planeta": "Gene Lab",
        "historia": "Científico loco que experimente consigo mismo. Su cuerpo es un实验室 viviente.",
        "poderes": ["Adaptacion", "Mutacion rapida", "Regeneracion"],
        "armas": ["Aparatos cientificos", "Armas biologicas"],
        "enemigos": ["Etica", "Autoridades", "Su creación"],
        "amigos": ["Criaturas", "Experimentos"],
        "faccion": "Ciencia",
    },
    {
        "id": 45,
        "nombre": "ARES",
        "edad": "5000",
        "raza": "Dios Guerrrero",
        "clase": "Dios",
        "planeta": "Olympus",
        "historia": "Dios de la guerra de una civilización antigua. Ahora lucha por entretenimiento.",
        "poderes": ["Poder divino", "Inmortalidad", "Manipulacion de conflicto"],
        "armas": ["Espada de Ares", "Escudo de guerra"],
        "enemigos": ["Atenea", "Paz", "Humanidad"],
        "amigos": ["Guerreros", "Sangre"],
        "faccion": "Dioses",
    },
    {
        "id": 46,
        "nombre": "SIREN",
        "edad": "200",
        "raza": "Acuatica",
        "clase": "Cantante",
        "planeta": "Ocean World",
        "historia": "Su canto puede controlar mentes. Rey del océano y sus profundidades.",
        "poderes": ["Control mental por sonido", "Respiracion acuática", "Seducción"],
        "armas": ["Tridente", "Canto mortal"],
        "enemigos": ["Barcos", "Caçadores", "Mar"],
        "amigos": ["Mar", "Peces"],
        "faccion": "Reino Acuático",
    },
    {
        "id": 47,
        "nombre": "ZENITH",
        "edad": "35",
        "raza": "Humano",
        "clase": "Ascendido",
        "planeta": "The Peak",
        "historia": "Alcanzó la iluminación suprema. Su mente puede doblar la realidad.",
        "poderes": ["Telequinesis", "Psicosis", "Realidad mutable"],
        "armas": ["Mente", "Energia Psionica"],
        "enemigos": ["Locura", "Caos", "Psicopatas"],
        "amigos": ["Iluminados", "Maestros"],
        "faccion": "Orden Ascendida",
    },
    {
        "id": 48,
        "nombre": "REAPER",
        "edad": "10000",
        "raza": "Muerte",
        "clase": "Segador",
        "planeta": "El Más Allá",
        "historia": "La muerte misma. Recolecta almas cuando llega su momento.",
        "poderes": ["Control de muerte", "Necromancia", "Inmortalidad"],
        "armas": ["Guadaña de la Muerte", "Libro de los muertos"],
        "enemigos": ["Vida", "Inmortales", "Dioses"],
        "amigos": ["Ninguno", "La Muerte"],
        "faccion": "La Muerte",
    },
    {
        "id": 49,
        "nombre": "ATLAS",
        "edad": "5000",
        "raza": "Titán",
        "clase": "Sostenedor",
        "planeta": "Space Station",
        "historia": "Sostiene el peso del universo sobre sus hombros. Literalmente.",
        "poderes": ["Fuerza infinita", "Resistencia maxima", "Peso controlable"],
        "armas": ["Columna celestial", "Manos de atlas"],
        "enemigos": ["Gravedad", "Colapso", "El Cielo"],
        "amigos": ["Universo", "Cielo"],
        "faccion": "Sostenedores",
    },
    {
        "id": 50,
        "nombre": "ZERO",
        "edad": "0",
        "raza": "Nulo",
        "clase": "Vacío",
        "planeta": "La Nada",
        "historia": "Nacido del cero absoluto. Existe como la ausencia de existencia.",
        "poderes": ["Aniquilacion", "Creacion desde cero", "Nulidad"],
        "armas": ["El Vacio", "Nada"],
        "enemigos": ["Existencia", "Todo", "Algo"],
        "amigos": ["Nada", "Vacío"],
        "faccion": "Nulo",
    },
]


def obtener_personaje(id_personaje):
    for p in PERSONAJES_PREDEFINIDOS:
        if p["id"] == id_personaje:
            return p
    return None


def obtener_personajes_por_faccion(faccion):
    return [p for p in PERSONAJES_PREDEFINIDOS if p.get("faccion") == faccion]


def listar_facciones():
    return list(set([p.get("faccion", "Unknown") for p in PERSONAJES_PREDEFINIDOS]))


def buscar_personaje_por_nombre(nombre):
    nombre_lower = nombre.lower()
    for p in PERSONAJES_PREDEFINIDOS:
        if nombre_lower in p["nombre"].lower():
            return p
    return None


def obtener_todos_los_nombres():
    return [p["nombre"] for p in PERSONAJES_PREDEFINIDOS]
